project:
  type: website
  output-dir: docs

website:
  title: "STA 199"
  sidebar:
    background: "#00539B"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/sta210-s22/website
        text: GitHub
      - icon: cloud-fill
        href: https://cmgr.oit.duke.edu/containers
        text: RStudio Containers
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule

format:
  html:
    theme:
      light: [cosmo, style/dsbox.scss]
      dark: [cosmo, style/dsbox.scss, style/dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    include-in-header: "style/fontawesome.html"

editor: visual